### ISSUE TITLE
[FEATURE] Break console exporter up by suite

### ISSUE THREAD

**Issue by jonnyboyC** [Dynatrace/zakzak#43]
Hi 👋 , first off let me say this has been an awesome find and something I've been looking for some time. I've been playing around with including this my side project and have started to incorporate this project so I can better monitor performance regression / improvements. [Here](https://github.com/jonnyboyC/kos-language-server/tree/master/server/benchmark) is some small folder of the first couple benchmarks I've thrown together. 

What I've found might be useful is breaking up the default console exporter by suite.  Essentially have the table that is already there with may a title line to the suite path.

## Detailed Description
Here is an example of what I'm thinking.
```js
suite('some service or class 1', () => {
  benchmark('some data 1', () => { /* ... */ });
  benchmark('some data 2', () => { /* ... */ });
});

suite('some service or class 2', () => {
  benchmark('some data 1', () => { /* ... */ });
  benchmark('some data 2', () => { /* ... */ });
});
```

Here, the default console exporter will show `some data 1` and `some data 2` twice. This can be somewhat confusing to figure out which line item corresponds to which benchmark unless you have some intuition on when one bench would be significantly faster than the the other.

I think in this case it could be great if the exporter showed a table for `some service or class 1` and a different table for `some service or class 2`. I think this could be extended for many nested suites such as `grandparent suite >> parent suite >> child suite` then the table of benchmarks in the child suite.

## Context
Obviously, this is still very early in the project but I think this will give a better experience overall because the core idea / implementation is great!

## Possible Implementation
I'd have to dig into the BenchmarkResult interface but I believe you can already determine the suite with something like this.

```js
onResult(result: BenchmarkResult): void {
  const relativeId = relative(__dirname, result.id);
  const suites = relativeId.split(':');
  console.log(`${suites[0]} >> ${suites.slice(1).join(' >> ')}`);
}
```

## Your Environment

* Version used: 0.5.0
* Environment name and version (e.g. node 10.15.2 and npm 6.4.1): Have to double check but I believe 12.x.x and the latest npm
* Operating System and version: Ubuntu 19.10
* Link to your project: https://github.com/jonnyboyC/kos-language-server

**Comment by lukaskurz** [comment]
@jonnyboyC I have been thinking about this for some time, hence why i built the "hierarchy" exporter to address the lack of information about the suites. I think this should be easily doable with the default "console" exporter. However I have some concerns with the "console-async" exporter combined with parallel benchmark execution, so i probably won't extend this functionality to the "console-async" exporter.

**Comment by lukaskurz** [comment]
@jonnyboyC the feature you described should now be working with the "console" exporter.

**Comment by jonnyboyC** [comment]
> However I have some concerns with the "console-async" exporter combined with parallel benchmark execution, so i probably won't extend this functionality to the "console-async" exporter.

I think this makes a lot of sense since the the async case is inherently more complicated to coordinate. Thanks for looking at this so quickly!
